# Generated by Django 5.2.13 on 2026-04-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('total_received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
