# Generated by Django 5.2.13 on 2026-04-26 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0002_remove_bankstatement_user_and_more'),
        ('document', '0001_initial'),
        ('invoicemanagement', '0002_alter_invoice_options_alter_invoicelineitem_options_and_more'),
        ('paymentadvice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('failed', 'Failed'), ('manual_review', 'Manual Review')], default='pending', max_length=20)),
                ('reconciliation_date', models.DateTimeField(auto_now_add=True)),
                ('amount_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('matching_confidence', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanagement.invoice')),
                ('payment_advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentadvice.paymentadvice')),
            ],
        ),
    ]
