# Generated by Django 5.2.13 on 2026-04-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_reconciliation'),
        ('invoicemanagement', '0002_alter_invoice_options_alter_invoicelineitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to='invoicemanagement.invoice'),
        ),
    ]
