# Generated by Django 5.2.13 on 2026-04-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_reconciliation_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='stopped', max_length=20)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable/disable the entire scheduler')),
                ('parser_enabled', models.BooleanField(default=True, help_text='Enable bank statement parsing job')),
                ('parser_interval', models.PositiveIntegerField(default=60, help_text='Parser interval in seconds (10-3600)')),
                ('reconciliation_enabled', models.BooleanField(default=False, help_text='Enable bank reconciliation job')),
                ('reconciliation_interval', models.PositiveIntegerField(default=60, help_text='Reconciliation interval in seconds (10-3600)')),
                ('email_parser_enabled', models.BooleanField(default=False, help_text='Enable email parsing job')),
                ('email_parser_interval', models.PositiveIntegerField(default=300, help_text='Email parser interval in seconds (10-3600)')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('job_count', models.PositiveIntegerField(default=0, help_text='Total jobs executed')),
                ('process_id', models.PositiveIntegerField(blank=True, help_text='Current scheduler process ID', null=True)),
                ('host_info', models.CharField(blank=True, help_text='Host where scheduler is running', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduler Configuration',
                'verbose_name_plural': 'Scheduler Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
