# Generated by Django 4.2.7 on 2026-04-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('invoicemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='document.document'),
        ),
    ]
