# Generated by Django 5.2.13 on 2026-04-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('invoicemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_no',
            new_name='extraction_method',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_date',
            new_name='invoicedate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='is_matched',
        ),
        migrations.AddField(
            model_name='invoice',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='document.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoiceNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('processed', 'Processed'), ('validated', 'Validated'), ('error', 'Error')], default='draft', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entries', to='invoicemanagement.invoice'),
        ),
    ]
