# Generated by Django 5.2.13 on 2026-04-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_reconciliation_invoice'),
        ('invoicemanagement', '0002_alter_invoice_options_alter_invoicelineitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_reconciliation', to='document.reconciliation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reconciliation_status',
            field=models.CharField(choices=[('unreconciled', 'Unreconciled'), ('matched', 'Matched'), ('manual_review', 'Manual Review'), ('failed', 'Failed')], default='unreconciled', max_length=20),
        ),
    ]
