# Generated by Django 5.2.13 on 2026-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0002_remove_bankstatement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='txn_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
