# Generated by Django 4.2.7 on 2026-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0002_alter_bankstatement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='number_of_txn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='total_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='total_debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
