# Generated by Django 5.2.13 on 2026-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0003_banktransaction_txn_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='total_receivable_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
