# Generated by Django 4.2.7 on 2026-04-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0003_bankstatement_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='user',
        ),
    ]
